<?php include "globals.php" ?>
<?php include "utils.php" ?>
<?php include "mysql.php" ?>

<?php
   // Get query params
   $deviceID = $_GET["deviceID"]; 
   $model = $_GET["model"];
   $lat = $_GET["lat"]; 
   $lon = $_GET["lon"]; 
   $ts = $_GET["ts"];
   $headers = apache_request_headers();
   $hash = $headers['Authorization'];

   // Check to see if ts (ie. timestamp) exceeds 30s
   $time = time();
   if (abs($time - $ts) > 30) {
      http_response_code(403); 
      error_log("Request has overdue timestamp");
      exit;
   }
   
   // Check to see if hash is correct
   $h = hmac($ts, $secret);
   if ($hash != $h) {
      http_response_code(403); 
      error_log("Request has incorrect hash");
      error_log("Request: " . $hash . " Calc:" . $h);
      exit;
   }

   // Check to see if "deviceID" exists
   // If exists, check to see if model has changed. 
   //    If changed send back error. 
   //    Else update timestamp in DB with Now() 
   // If not exists, insert new entry with timestamp in DB as Now()
   // and send out email that new device was added
   $exists = entryExists($con, $deviceID, $model);
   $dupe = duplicateEntryExists($con, $deviceID, $model);
   if ($dupe  == "DUPLICATE") {
      http_response_code(409); 
      error_log("Request is for duplicate deviceID");
      sendmail($mailinglist, $subjectPrefix . "Error: device ID " . $deviceID . " already being used. Choose another", "THIS IS AN AUTOGENERATED MESSAGE<p><p>Device " . $deviceID . " already being used. Choose another.<p>");      
      exit;
   } elseif ($exists == TRUE) {
      $result = updateEntry($con, $deviceID, $model, $lat, $lon);
   } elseif ($exists == FALSE) {
      $result = insertNewEntry($con, $deviceID, $model, $lat, $lon);
      sendmail($mailinglist, $subjectPrefix . "New device added - " . $deviceID, "THIS IS AN AUTOGENERATED MESSAGE<p><p>Device " . $deviceID . " has been added for tracking<p>");      
   } else {
      // I need to figure out what to put here
      echo $exists;
   }
?>
